# NUMPY PRACTICE QUESTIONS 

In [1]:
import numpy as np

### 1. Create a null vector of size 10 but the fifth value which is 1.

In [3]:
arr = np.zeros(10)
arr[4] = 1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


### 2. Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b)           and print the array and avg of the array.

In [4]:
a, b = map(int, input().split())
arr = np.random.random((a, b))
print(arr)
print(f'Average: {np.average(arr)}')

 5 6


[[0.65601912 0.98216915 0.28558499 0.53369956 0.85866909 0.4460347 ]
 [0.36249006 0.11571303 0.48496578 0.65690169 0.88181255 0.34097053]
 [0.65390226 0.87010875 0.22705985 0.64154457 0.65494694 0.34581602]
 [0.78451509 0.00683152 0.80016693 0.42047107 0.83700377 0.06886372]
 [0.66686023 0.98733441 0.00454225 0.13233933 0.74325191 0.61912521]]
Average: 0.5356571361698551


### 3. Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [5]:
def matrix_func(a, b):
    arr = np.ones((a, b))
    arr[1:-1, 1:-1] = 0
    print(arr)

a, b = map(int, input().split())
matrix_func(a, b)

 10 11


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


### 4. Create a vector of size 10 with values ranging from 0 to 1, both excluded.

In [7]:
arr = np.linspace(0, 1, 12)[1:-1]
print(arr)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


### 5. Create a 5x5 matrix with row values ranging from 0 to 4.

> Method # 1

In [31]:
arr = np.tile(np.arange(0, 5), (5,1))
print(arr)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


> Method # 2

In [32]:
arr = np.vstack([np.arange(0, 5) for _ in range(5)])
print(arr)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


### 6. Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3]) 
```


> Method # 1:

In [60]:
def euc_distance(x, y):
    point = np.array([2, 3])
    return np.round(((x - point[0]**2) + (y - point[1]**2))**0.5, 2)


rng = np.random.default_rng()
arr = rng.integers(1, 100, 20).reshape(10, 2)
for cor in arr:
    print(f'Distance from {cor} = {euc_distance(cor[0], cor[1])}')

Distance from [62 64] = 10.63
Distance from [25 31] = 6.56
Distance from [16 84] = 9.33
Distance from [23 86] = 9.8
Distance from [48 22] = 7.55
Distance from [62 27] = 8.72
Distance from [89 29] = 10.25
Distance from [ 3 29] = 4.36
Distance from [73 15] = 8.66
Distance from [33 40] = 7.75


> Method # 2:

In [63]:
def euc_distance(arr):
    point = np.array([2, 3])
    return np.linalg.norm(arr - point, axis=1)

arr = np.random.randint(1, 101, size=(10, 2))
res = euc_distance(arr)
for i in range(10):
    print(f'Distance from {arr[i]} = {np.round(res[i], 2)}')

Distance from [94 59] = 107.7
Distance from [74 76] = 102.53
Distance from [72 64] = 92.85
Distance from [54 38] = 62.68
Distance from [83 18] = 82.38
Distance from [12 70] = 67.74
Distance from [76  4] = 74.01
Distance from [72 87] = 109.34
Distance from [73 29] = 75.61
Distance from [59 45] = 70.8


### 7. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [74]:
arr = np.arange(6*7*8).reshape(6, 7, 8)
print(f'100th element = {arr[1, 5, 3]}') # or arr[1, -2, 3]

100th element = 99


### 8. You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.
**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```


In [82]:
inp = list(map(int, input().split()))
arr = np.array(inp)
rev = arr[::-1].astype(float)
print(f'INput: {arr}\nOutput: {rev}')

 1 -12 -90 0 8 5


INput: [  1 -12 -90   0   8   5]
Output: [  5.   8.   0. -90. -12.   1.]


### 10. Count the number of elements of a numpy array.
**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [89]:
inp = list(map(int, input().split()))
arr = np.array(inp)
print(f'Number of elements = {arr.size}')

 1 2 4 21 2 0 13


Number of elements = 7


### 10. Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function

**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01, 
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [109]:
def softmax(arr):
    if arr.size == 0:
        raise Exception("Array is empty")
    sigma = np.sum(np.exp(arr))
    for index, el in enumerate(arr):
        arr[index] = np.exp(el) / sigma
    return arr

In [112]:
inp = list(map(float, input().split()))
arr = np.array(inp)
try:    
    arr = softmax(arr)
    print(f'Result = {arr}')
except Exception as e: 
    print(e)

 33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278


Result = [4.57181033e-26 1.16249922e-20 7.73872594e-05 2.60358426e-05
 1.39571531e-10 9.99896577e-01]


### 11. Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.

**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]] 
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```