# NUMPY PRACTICE QUESTIONS 

In [2]:
import numpy as np

### 1. Create a null vector of size 10 but the fifth value which is 1.

In [3]:
arr = np.zeros(10)
arr[4] = 1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


### 2. Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b)           and print the array and avg of the array.

In [4]:
a, b = map(int, input().split())
arr = np.random.random((a, b))
print(arr)
print(f'Average: {np.average(arr)}')

 5 6


[[0.72618191 0.24323005 0.44723617 0.02654674 0.17051602 0.12853483]
 [0.95850096 0.2966085  0.76993215 0.51356365 0.16703802 0.74441498]
 [0.52335347 0.02671501 0.24411168 0.9312998  0.47612177 0.40266492]
 [0.84777494 0.91482263 0.50631563 0.91023356 0.99645241 0.18382375]
 [0.8338564  0.02100294 0.98540925 0.55630586 0.49891022 0.99193778]]
Average: 0.5347805325401538


### 3. Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [5]:
def matrix_func(a, b):
    arr = np.ones((a, b))
    arr[1:-1, 1:-1] = 0
    print(arr)

a, b = map(int, input().split())
matrix_func(a, b)

 6 7


[[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


### 4. Create a vector of size 10 with values ranging from 0 to 1, both excluded.

In [6]:
arr = np.linspace(0, 1, 12)[1:-1]
print(arr)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


### 5. Create a 5x5 matrix with row values ranging from 0 to 4.

> Method # 1

In [7]:
arr = np.tile(np.arange(0, 5), (5,1))
print(arr)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


> Method # 2

In [8]:
arr = np.vstack([np.arange(0, 5) for _ in range(5)])
print(arr)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


### 6. Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3]) 
```


> Method # 1:

In [9]:
def euc_distance(x, y):
    point = np.array([2, 3])
    return np.round(((x - point[0]**2) + (y - point[1]**2))**0.5, 2)


rng = np.random.default_rng()
arr = rng.integers(1, 100, 20).reshape(10, 2)
for cor in arr:
    print(f'Distance from {cor} = {euc_distance(cor[0], cor[1])}')

Distance from [28 40] = 7.42
Distance from [29 22] = 6.16
Distance from [97 32] = 10.77
Distance from [52 87] = 11.22
Distance from [55 12] = 7.35
Distance from [22 49] = 7.62
Distance from [56 83] = 11.22
Distance from [15 58] = 7.75
Distance from [11 12] = 3.16
Distance from [49 88] = 11.14


> Method # 2:

In [10]:
def euc_distance(arr):
    point = np.array([2, 3])
    return np.linalg.norm(arr - point, axis=1)

arr = np.random.randint(1, 101, size=(10, 2))
res = euc_distance(arr)
for i in range(10):
    print(f'Distance from {arr[i]} = {np.round(res[i], 2)}')

Distance from [ 7 98] = 95.13
Distance from [81  1] = 79.03
Distance from [53 98] = 107.82
Distance from [ 4 95] = 92.02
Distance from [87 95] = 125.26
Distance from [21 25] = 29.07
Distance from [34 27] = 40.0
Distance from [86 39] = 91.39
Distance from [45 68] = 77.94
Distance from [17 69] = 67.68


### 7. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [11]:
arr = np.arange(6*7*8).reshape(6, 7, 8)
print(f'100th element = {arr[1, 5, 3]}') # or arr[1, -2, 3]

100th element = 99


### 8. You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.
**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```


In [12]:
inp = list(map(int, input().split()))
arr = np.array(inp)
rev = arr[::-1].astype(float)
print(f'INput: {arr}\nOutput: {rev}')

 54 -9 0 12 33 -91


INput: [ 54  -9   0  12  33 -91]
Output: [-91.  33.  12.   0.  -9.  54.]


### 10. Count the number of elements of a numpy array.
**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [13]:
inp = list(map(int, input().split()))
arr = np.array(inp)
print(f'Number of elements = {arr.size}')

 9 28 22 2 1


Number of elements = 5


### 10. Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function

**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01, 
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [14]:
def softmax(arr):
    if arr.size == 0:
        raise Exception("Array is empty")
    sigma = np.sum(np.exp(arr))
    for index, el in enumerate(arr):
        arr[index] = np.exp(el) / sigma
    return arr

In [15]:
inp = list(map(float, input().split()))
arr = np.array(inp)
try:    
    arr = softmax(arr)
    print(f'Result = {arr}')
except Exception as e: 
    print(e)

 33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278


Result = [4.57181033e-26 1.16249922e-20 7.73872594e-05 2.60358426e-05
 1.39571531e-10 9.99896577e-01]


### 11. Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.

**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]] 
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [25]:
def stack_func(*args):
    if all(isinstance(arg, np.ndarray) for arg in args):
        res = np.vstack(args)
        print(res)
    else:
        raise Exception("Wrong type")

In [28]:
try:
    stack_func(np.array([i for i in range(10)]).reshape(2, 5), np.ones((2, 5)), np.random.random((2, 5)))
except Exception as e:
    print(e)

[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.76920031 0.70267404 0.74680348 0.78858109 0.61797074]
 [0.1913889  0.28837937 0.71932731 0.16062536 0.356567  ]]


### 12. Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.

**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [37]:
def find_date(date_1, date_2):
    if not isinstance(date_1, str) or not isinstance(date_2, str):
        raise Exception("Wrong type")
    
    date_format = "%Y-%m-%d"

    try:
        start = np.datetime64(date_1, 'D')
        end = np.datetime64(date_2, 'D')
    except ValueError:
        raise Exception("Incorrect format")

    if start.astype('datetime64[Y]') != end.astype('datetime64[Y]'):
        raise Exception("Years should be same")

    total_days = (end - start).astype(int) + 1
    arr = np.arange(start, start + np.timedelta64(total_days, 'D'))

    return arr

In [39]:
try:
    date_arr = find_date('2020-09-15', '2020-09-25')
    print(date_arr)
except Exception as e:
    print(e)

['2020-09-15' '2020-09-16' '2020-09-17' '2020-09-18' '2020-09-19'
 '2020-09-20' '2020-09-21' '2020-09-22' '2020-09-23' '2020-09-24'
 '2020-09-25']


### 13. Subtract the mean of each row from a matrix.

In [72]:
arr = np.arange(10).reshape(2,5)
m_arr = np.mean(arr, axis=1, keepdims=True)
res = arr - m_arr
print(f'~ Original:\n{arr}\n~ Mean of each row:\n{m_arr}\n~ After subtraction:\n{res}')

~ Original:
[[0 1 2 3 4]
 [5 6 7 8 9]]
~ Mean of each row:
[[2.]
 [7.]]
~ After subtraction:
[[-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]]


### 14. Swap column-1 of array with column-2 in the array.

In [78]:
arr = np.linspace(0, 20, 10).reshape(5, 2)
print(f'~ Before:\n{arr}')
arr[:, [1, 0]] = arr[:, [0, 1]]
print(f'~ After:\n{arr}')

~ Before:
[[ 0.          2.22222222]
 [ 4.44444444  6.66666667]
 [ 8.88888889 11.11111111]
 [13.33333333 15.55555556]
 [17.77777778 20.        ]]
~ After:
[[ 2.22222222  0.        ]
 [ 6.66666667  4.44444444]
 [11.11111111  8.88888889]
 [15.55555556 13.33333333]
 [20.         17.77777778]]


### 15. Replace odd elements in arrays with -1.

In [90]:
arr = np.arange(0, 20).reshape(5, 4)
print(f'~ Before:\n{arr}')
odd_el = arr % 2 != 0
arr[odd_el] = -1
print(f'~ After:\n{arr}')

~ Before:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
~ After:
[[ 0 -1  2 -1]
 [ 4 -1  6 -1]
 [ 8 -1 10 -1]
 [12 -1 14 -1]
 [16 -1 18 -1]]


### 16. Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
``` 

In [93]:
def max_arr(arr_1, arr_2):
    max_arr = np.maximum(arr_1, arr_2)
    print(f'~ Array 1:\n{arr_1}\n~ Array 2:\n{arr_2}\n~ Max array:\n{max_arr}')

max_arr(np.array([6,3,1,5,8]), np.array([3,2,1,7,2]))

~ Array 1:
[6 3 1 5 8]
~ Array 2:
[3 2 1 7 2]
~ Max array:
[6 3 1 7 8]


### 17. Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [94]:
arr1 = np.random.randint(low=1, high=10000, size=40).reshape(8,5)
print(arr1)

[[4977 9810 8448 2117 2551]
 [3610 2879 5827 1785 2325]
 [9322 9850 6039 4509  714]
 [3436 5709 5671 9438 5459]
 [5082 5312 1196 2932 9783]
 [8846 7832 5059 5406 4226]
 [6979 3412 8506 9821 7909]
 [9591 2883  954 2146 4262]]


> Part # 1:

In [96]:
print(arr1[:,::2])

[[4977 8448 2551]
 [3610 5827 2325]
 [9322 6039  714]
 [3436 5671 5459]
 [5082 1196 9783]
 [8846 5059 4226]
 [6979 8506 7909]
 [9591  954 4262]]


> Part # 2:

In [104]:
def normalize(arr):
    x_min = np.min(arr)
    x_max = np.max(arr)
    
    return (arr - x_min) / (x_max - x_min)

x_norm = normalize(arr1)
print(x_norm)

[[0.46661559 0.99562172 0.84654116 0.1535683  0.20107268]
 [0.31698774 0.23697461 0.55965412 0.11722855 0.17633538]
 [0.94220665 1.         0.58285902 0.41538967 0.        ]
 [0.29794221 0.54673818 0.54257881 0.95490368 0.51937391]
 [0.47810858 0.50328371 0.05275832 0.24277583 0.99266637]
 [0.89010508 0.77911559 0.47559107 0.51357268 0.38441331]
 [0.68574869 0.29531524 0.85288967 0.99682574 0.78754378]
 [0.97165061 0.23741243 0.0262697  0.15674256 0.38835377]]


### 18. Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [116]:
def n_max(arr, n):
    if n > len(arr):
        raise Exception("n should be less than equal to array length")
    return np.sort(arr)[len(arr) - n]

try:
    arr = np.random.randint(low=0, high=90, size=10)
    n = 6
    n_max_el = n_max(arr, n)
    print(f'Array = {arr} and n = {n}, ouptut = {n_max_el}')
except Exception as e:
    print(e)

Array = [82 18 77 57 38 79 47 49 86 38] and n = 6, ouptut = 49


### 19. Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [119]:
def pattern(arr):
    return np.hstack((np.repeat(arr, 3), np.tile(arr, 3)))

a = np.array([1,2,3])
print(pattern(a))

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]
